apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - image: bitelio/api
        name: api
        envFrom:
          - configMapRef:
              name: api
        ports:
          - containerPort: 80
            name: http
